"""Dispatcher's vocabulary: structured reason codes only — no keyword
tables, since nothing in Dispatcher reads free text (Lead Qualifier already
did that upstream; Dispatcher only combines already-structured fields).
Kept separate from dispatcher_engine.py so the engine module contains only
classification logic, same split as lead_qualifier_rules.py/
lead_qualifier_engine.py.
"""

REASON_PRIORITY_URGENCY_EMERGENCY = "PRIORITY_URGENCY_EMERGENCY"
REASON_PRIORITY_URGENCY_SAME_DAY = "PRIORITY_URGENCY_SAME_DAY"
REASON_PRIORITY_QUALIFIER_HIGH_BUMP = "PRIORITY_QUALIFIER_HIGH_BUMP"
REASON_PRIORITY_NORMAL_NO_SIGNAL = "PRIORITY_NORMAL_NO_SIGNAL"

REASON_WINDOW_EMERGENCY_IMMEDIATE = "WINDOW_EMERGENCY_IMMEDIATE"
REASON_WINDOW_SAME_DAY_TODAY = "WINDOW_SAME_DAY_TODAY"
REASON_WINDOW_REPAIR_TOMORROW = "WINDOW_REPAIR_TOMORROW"
REASON_WINDOW_FLEXIBLE_JOB_TYPE = "WINDOW_FLEXIBLE_JOB_TYPE"

REASON_REVIEW_POSSIBLE_SPAM = "REVIEW_POSSIBLE_SPAM"
REASON_REVIEW_MISSING_CALLBACK = "REVIEW_MISSING_CALLBACK"
REASON_REVIEW_MISSING_ADDRESS = "REVIEW_MISSING_ADDRESS"
REASON_REVIEW_EMERGENCY_ALERT_UNCONFIRMED = "REVIEW_EMERGENCY_ALERT_UNCONFIRMED"
REASON_REVIEW_NO_SIGNAL = "REVIEW_NO_SIGNAL"
