"""Membership Agent's pure pieces: delays, message templates, the reply tool
schema, and the classification prompt. No DB or AgentEngine imports here —
mirrors review_engine.py and referral_engine.py, so each employee stays
independent of the others' module structure.

Design doc: docs/superpowers/specs/2026-08-10-gen-2-workforce-design.md §4.1.
"""

import os


def _delay_days(name: str, default: float) -> float:
    """Same helper (and same reasoning) as review_engine._delay_days: both
    delays are env-overridable so an end-to-end test can run in one sitting
    instead of waiting a week, without a test-only "send now" route living
    permanently in production. A malformed value falls back to the default
    rather than crashing boot."""
    try:
        return float(os.environ.get(name, default))
    except (TypeError, ValueError):
        return default


# WHY 7 DAYS, AND WHY THIS NUMBER IS NOT ARBITRARY: a completed job already
# triggers three outbound texts from other employees — the Reviews ask
# (REVIEW_DELAY_DAYS=1), the Referral ask (REFERRAL_DELAY_DAYS=4), and the one
# Reviews follow-up (~day 5). No employee knows what another sent
# (design doc §2.4), so the ONLY thing keeping a customer's week from becoming
# a stream of texts from four different "people" at the same business is this
# ordering. Day 7 puts the membership offer after all three have cleared.
#
# This is a deliberate stopgap, not a solution: it is a constant chosen to
# dodge other constants, and it silently stops working if REVIEW_DELAY_DAYS or
# REFERRAL_DELAY_DAYS is raised in the environment. The real fix is the Chief
# of Staff owning outbound contention centrally (design doc §4.2).
# ponytail: ordering by constant; replace with a shared "has anyone texted
# this customer in the last N days" check when the 5th outbound employee lands.
MEMBERSHIP_OFFER_DELAY_DAYS = _delay_days("MEMBERSHIP_OFFER_DELAY_DAYS", 7)

# One nudge, well after the offer. There is never a third touch — a structural
# cap, not a runtime "have we annoyed them yet" judgment, the same guarantee
# Reviews makes with review_followup_sent_at.
MEMBERSHIP_FOLLOWUP_DELAY_DAYS = _delay_days("MEMBERSHIP_FOLLOWUP_DELAY_DAYS", 5)

# How long after the offer an inbound text is still assumed to be about it.
# Bounded for the same reason find_active_referral_ask is: without a bound, an
# unrelated text months later would still match and be misrouted forever.
MEMBERSHIP_REPLY_WINDOW_DAYS = 14

# The plan text is the owner's own words, quoted verbatim from
# Business.membership_plan — the agent never describes, summarizes, or
# embellishes what the plan includes, because it has no way to know. Voice
# follows DESIGN.md: warm, blunt, plain, no jargon, no marketing verbs.
MEMBERSHIP_OFFER_TEMPLATE = (
    "Hi {customer_name}, thanks again for having us out for the "
    "{service_type}. One thing worth knowing about: {membership_plan} "
    "Want me to get you set up?"
)

# Deliberately does NOT repeat the whole plan text — it's nudging someone who
# has already read it once — and it gives an explicit easy out, so declining
# costs the customer nothing.
MEMBERSHIP_FOLLOWUP_TEMPLATE = (
    "Hi {customer_name}, just circling back on the maintenance plan I "
    "mentioned. Happy to set it up whenever — or say no thanks and I'll "
    "leave it be."
)


class _SafeDict(dict):
    def __missing__(self, key):
        return ""


def render_membership_template(text: str, **variables) -> str:
    return text.format_map(_SafeDict(variables))


RECORD_MEMBERSHIP_REPLY_TOOL = {
    "name": "record_membership_reply",
    "description": (
        "Call this after reading the customer's reply to a maintenance plan "
        "offer. Classify what they actually communicated — never assume they "
        "agreed unless they clearly said so."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "intent": {
                "type": "string",
                "enum": ["accepted", "declined", "question", "unsubscribe", "unclear"],
                "description": (
                    "accepted: they clearly want the plan (yes, sign me up, sounds good). "
                    "declined: they clearly don't want it, or want to think about it / not right now. "
                    "question: they're interested but asked something first — price, what's "
                    "covered, how billing works, whether it's worth it. "
                    "unsubscribe: they asked to stop being contacted. "
                    "unclear: the reply doesn't clearly fit any of the above."
                ),
            },
        },
        "required": ["intent"],
    },
}

# Hardcoded per-intent customer-facing replies — never generated by the model.
# A code-level guarantee, not a prompt-following hope, that the agent never
# quotes a price, invents a plan term, promises a start date, or confirms
# billing it cannot actually set up.
#
# "accepted" is worded to be literally true about what just happened: Roster
# recorded the yes and told the owner. Roster cannot charge a card, so the
# owner finalizes it — promising more than that would be the first lie this
# product tells a real customer.
OUTCOME_REPLIES = {
    "accepted": (
        "That's great — I've put you down for it and passed it to the office. "
        "They'll confirm the details with you and get it started."
    ),
    "declined": "No problem at all — thanks for letting me know!",
    "question": ("Good question — let me have someone from the office get back to you on that."),
    "unsubscribed": (
        "You've been unsubscribed and won't receive further messages. Reply START to resume."
    ),
    "unclear": ("Thanks for getting back to me! I'll have someone from the office follow up."),
}


def build_membership_reply_prompt(plan_text: str) -> str:
    """The plan text is passed in so the model can tell an on-topic question
    from an unrelated one — NOT so it can answer the question. Every question,
    including one the plan text plainly answers, is classified as `question`
    and handed to the owner: the model has no way to know whether the owner's
    blurb is current, complete, or applies to this customer."""
    return (
        "You offered this customer the following maintenance plan by text, in "
        f"the business's own words:\n\n{plan_text}\n\n"
        "Read their reply and call record_membership_reply with the intent "
        "that best matches what they actually said. Do not treat politeness "
        "or interest as agreement — 'sounds interesting' or 'let me think' is "
        "not 'accepted'. If they asked anything at all about the plan, "
        "classify it as 'question' even if the text above appears to answer "
        "it; a person from the office will respond, not you. Do not answer "
        "questions, quote prices, or describe what the plan covers yourself."
    )
