"""Reviews' pure pieces: constants and the message template. No DB or
AgentEngine imports here — mirrors referral_engine.py's own shape, which
deliberately does not import from recovery_engine.py either, so each of
Frontdesk/Recovery/Referral/Reviews stays independent of the others'
module structure.
"""

# "Wait an appropriate amount of time" (2026-07-29 plan) before the first
# ask, rather than the instant send this replaces — a day lets the work
# settle before asking. One follow-up only, well after the first ask, never
# more than once (2026-07-30: negative-sentiment handling and the
# never-spam guarantee both depend on this staying a two-touch maximum).
#
# Both delays are env-overridable so an end-to-end test on a real deployment
# can run in one sitting (REVIEW_DELAY_DAYS=0) instead of waiting a day for
# the first text — the alternative was a test-only "send now" route living
# permanently in production. Fractional days are allowed (0.01 ≈ 15 min).
# Defaults are the real product behaviour; a malformed value falls back to
# the default rather than crashing boot (same rule as
# app.scheduler_interval_seconds).
import os


def _delay_days(name: str, default: float) -> float:
    try:
        return float(os.environ.get(name, default))
    except (TypeError, ValueError):
        return default


REVIEW_DELAY_DAYS = _delay_days("REVIEW_DELAY_DAYS", 1)
REVIEW_FOLLOWUP_DELAY_DAYS = _delay_days("REVIEW_FOLLOWUP_DELAY_DAYS", 4)
REVIEW_REPLY_WINDOW_DAYS = 14

# Same wording the old synchronous send in app.py already used — preserved
# verbatim, not rewritten, since it was already-approved copy.
REVIEW_MESSAGE_TEMPLATE = (
    "Thanks for choosing {business_name}! If we did right by you, a quick "
    "review means a lot: {review_link}"
)

# The one polite follow-up (PR #2) — distinct wording from the initial ask,
# not a repeat of it, since it's nudging someone who's already seen the ask
# once.
REVIEW_FOLLOWUP_MESSAGE_TEMPLATE = (
    "Hi again from {business_name} — just a friendly nudge in case you "
    "missed it: if you have a minute, a review would really help us out: "
    "{review_link}"
)


class _SafeDict(dict):
    def __missing__(self, key):
        return ""


def render_review_template(text: str, **variables) -> str:
    return text.format_map(_SafeDict(variables))


RECORD_REVIEW_REPLY_TOOL = {
    "name": "record_review_reply",
    "description": (
        "Call this after reading the customer's reply to a review request. "
        "Classify what they actually communicated — never guess or assume a "
        "review was left unless they said so."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "outcome": {
                "type": "string",
                "enum": ["left_review", "positive", "neutral", "negative", "declined", "unclear"],
                "description": (
                    "left_review: they said they already left/submitted a review. "
                    "positive: happy, no mention of having left a review yet. "
                    "neutral: acknowledged without clear sentiment either way. "
                    "negative: unhappy or dissatisfied. "
                    "declined: explicitly said they don't want to / won't leave one. "
                    "unclear: the reply doesn't clearly fit any of the above."
                ),
            },
        },
        "required": ["outcome"],
    },
}

# Hardcoded per-outcome customer-facing replies — never generated by the
# model. This is a code-level guarantee (not a prompt-following hope) that we
# never claim to have seen/verified a Google review, and that a dissatisfied
# customer is never handed the review link again.
OUTCOME_REPLIES = {
    "left_review": "Thank you so much, we really appreciate it!",
    "positive": "Thanks so much for the kind words!",
    "neutral": "Thanks for letting us know!",
    "negative": "We're sorry to hear that. Someone from our team will reach out to make it right.",
    "declined": "No worries at all, thanks for your time!",
    "unclear": "Thanks for getting back to us!",
}


def build_review_reply_prompt() -> str:
    return (
        "You just sent this customer a review request after completing their "
        "service. Read their reply and call record_review_reply with the "
        "outcome that best matches what they actually said. Do not assume "
        "they left a review unless they clearly said so. Do not invent or "
        "assume sentiment they didn't express."
    )
